### PR TITLE
Update repository URLs

### PR DESCRIPTION
**Pull request by steff456**
This PR is part of https://github.com/conda-incubator/jupyterlab-conda-store/issues/13

This PR,

- [x] Changes url that where pointing to Quansight org and replace it with conda-incubator org.
- [x] Adds a section for the Code of Conduct in the README.
- [x] Adds a section for the license in the README.

### CODE REVIEW

**Review by pavithraes — APPROVED** [review]
Thanks, @steff456! Looks good. :)

**Comment by steff456** [comment]
Let's wait for the CI to re-run, if it fails I'll check it locally

**Comment by anirrudh** [comment]
kk, this has been linted locally and I've update the PR!

**Review by anirrudh — APPROVED** [review]
LGTM

**Comment by steff456** [comment]
Thanks!!

**Pull request merged**
